from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

docs = [
    "Donor retention is defined as donors who gave last year and gave again this year.",
    "The campaign_metrics table is generated by the daily_campaign_pipeline.",
    "Client A ran a similar monthly giving campaign in 2023.",
]

model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(docs)

index = faiss.IndexFlatL2(embeddings.shape[1])
index.add(np.array(embeddings))
